version: '3'
services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 4406:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9111:80
    environment:
      PMA_HOST : 'mysql'
      PMA_USER : root
      PMA_PASSWORD : rootpassword
    depends_on:
      - mysql